Add GitHub Actions
Nymphium/grpc-ocaml pull request #1
Opened 2022-05-30 12:31 UTC by y-yu

🤔  https://github.com/y-yu/grpc-ocaml/runs/6654576467?check_suite_focus=true

```
Run opam exec -- dune build
(cd _build/default && /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I server/.grpc_server.objs/byte -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/angstrom -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/base_internalhash_types -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/caml -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/md5 -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/shadow_stdlib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base64 -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base_bigstring -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base_quickcheck -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bigarray-compat -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bigstringaf -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bin_prot -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bin_prot/shape -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/core -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/core/base_for_tests -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/core/validate -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/faraday -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/faraday-lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/faraday-lwt-unix -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/fieldslib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/gluten -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/gluten-lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/gluten-lwt-unix -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/h2 -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/h2-lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/h2-lwt-unix -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/hmap -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/hpack -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/httpaf -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/int_repr -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/jane-street-headers -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/logs -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/lwt/unix -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/lwt_ssl -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/mmap -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ocaml-protoc-plugin -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ocaml/threads -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ocplib-endian -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ocplib-endian/bigstring -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/parsexp -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_assert/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_bench/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_compare/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_deriving/runtime -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_enumerate/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_expect/collector -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_expect/common -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_expect/config -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_expect/config_types -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_hash/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_here/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_inline_test/config -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_inline_test/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_log/types -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_module_timer/runtime -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ppx_sexp_conv/runtime-lib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/psq -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/result -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/seq -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/sexplib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/sexplib0 -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/splittable_random -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/ssl -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/stdio -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/stringext -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/time_now -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/typerep -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/uri -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/variantslib -I basic/.Grpc_basic.objs/byte -no-alias-deps -opaque -open Grpc_server__ -o server/.grpc_server.objs/byte/grpc_server__Handler.cmo -c -impl server/handler.pp.ml)
File "server/handler.ml", line 23, characters 8-83:
23 |         (module PB.Service.Rpc with type Request.t = req and type Response.t = res)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Unbound module type PB.Service.Rpc
(cd _build/default && /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/bin/ocamlc.opt -w @1..3@5..28@30..39@43@46..47@49..57@61..62-40 -strict-sequence -strict-formats -short-paths -keep-locs -g -bin-annot -I client/.grpc_client.objs/byte -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/angstrom -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/base_internalhash_types -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/caml -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/md5 -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base/shadow_stdlib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base64 -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base_bigstring -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base_quickcheck -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/base_quickcheck/ppx_quickcheck/runtime -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bigarray-compat -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bigstringaf -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bin_prot -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/bin_prot/shape -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/core -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/core/base_for_tests -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/core/validate -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/faraday -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/faraday-lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/faraday-lwt-unix -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/fieldslib -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/gluten -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/gluten-lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/gluten-lwt-unix -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/h2 -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/h2-lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/h2-lwt-unix -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/hpack -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/httpaf -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/int_repr -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/jane-street-headers -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/logs -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/lwt -I /home/runner/work/grpc-ocaml/grpc-ocaml/_opam/lib/lwt/unix -I /home/runner/work/grpc-ocaml/grpc-o [...]

2022-05-30 13:15 UTC, Nymphium requested changes

2022-05-30 13:15 UTC, Nymphium commented on .github/workflows/ci.yml
> +        run: opam install . --deps-only --with-doc --verbose
This repo assumes to be built on Nix, so when CI uses opam it needs `opam pin add ocaml-protoc-plugin https://github.com/Nymphium/ocaml-protoc-plugin#create-rpc-path`.
Additionally, it requires `grpcurl`, `protobuf` and `yarn` for tests.
```suggestion
        run: |
          apt install protobuf grpcurl yarn # I don't know ubuntu has these pkgs or its correct name
          opam pin add ocaml-protoc-plugin https://github.com/Nymphium/ocaml-protoc-plugin#create-rpc-path
          opam install . --deps-only --with-doc --verbose
```

2022-06-01 07:39 UTC, Nymphium commented on .github/workflows/ci.yml
> +          opam pin add ocaml-protoc-plugin https://github.com/Nymphium/ocaml-protoc-plugin#create-rpc-path
It must has `.git`, my mistake
```suggestion
          opam pin add ocaml-protoc-plugin https://github.com/Nymphium/ocaml-protoc-plugin.git#create-rpc-path
```

2022-06-01 07:39 UTC, Nymphium commented on grpc.opam
> +  "fmt"
```suggestion
  "fmt" { with-test }
```

2022-06-08 16:48 UTC, y-yu commented
Success 🎉 
- https://github.com/y-yu/grpc-ocaml/runs/6797944105?check_suite_focus=true

2022-06-08 16:48 UTC, y-yu commented on grpc.opam
> +  "fmt"
🤔 

```
Run opam exec -- dune build
File "example/dune", line 3, characters 45-52:
3 |  (libraries grpc.server grpc.client logs.fmt fmt.tty))
                                                 ^^^^^^^
Error: Library "fmt.tty" not found.
-> required by _build/default/example/client.exe
-> required by alias example/all
-> required by alias default
```

https://github.com/y-yu/grpc-ocaml/runs/6797798509?check_suite_focus=true#step:5:1

2022-06-13 06:29 UTC, Nymphium commented on grpc.opam
> +  "fmt"
Sorry I myself misunderstood that `fmt` is not for test but for example😜

```suggestion
```

In addition, Dune automatically detects the build dependencies, so we dont't need `dune build` before `dune runtest`.

2022-06-13 09:23 UTC, y-yu commented on grpc.opam
> +  "fmt"
OK, I remove `dune build` and `fmt`.

2022-06-13 10:32 UTC, Nymphium approved these changes
Thank you🤗

2022-06-13 10:38 UTC, merged